/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.tprograms.view;

/**
 *
 * @author Titovilal
 */
public class SubPanelFavs extends javax.swing.JPanel {

    /**
     * Creates new form FavouritesPanel
     */
    public SubPanelFavs() {
        initComponents();
    }

    /**
     * Sets the text of a JButton with two lines, using HTML code to format the
     * text.
     *
     * @param playerName the player name to be displayed on the first line of
     * the button
     * @param region the region to be displayed on the second line of the button
     */
    public void setButtonText(String playerName, String region) {
        String text = "<html><center>" + playerName + "<br>" + region + "</center></html>";
        buttonAddFavourites.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAddFavourites = new javax.swing.JButton();

        setBackground(new java.awt.Color(43, 43, 43));
        setPreferredSize(new java.awt.Dimension(167, 57));

        buttonAddFavourites.setBackground(new java.awt.Color(43, 43, 43));
        buttonAddFavourites.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        buttonAddFavourites.setForeground(new java.awt.Color(204, 204, 204));
        buttonAddFavourites.setText("<html><center>Player name<br>Region</center></html>");
        buttonAddFavourites.setBorderPainted(false);
        buttonAddFavourites.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonAddFavourites, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonAddFavourites, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddFavourites;
    // End of variables declaration//GEN-END:variables
}
